import { Fragment, ReactNode, useState } from "react"
import Head from "next/head";
import { useRouter } from 'next/router'
import HeaderComponent from "@/components/header";
import FooterComponent from "@/components/footer"

type Props = {
  children: ReactNode
}
export default function BodyTemplate({ children }: Props) {
  const router = useRouter()

  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main>
        <HeaderComponent/>
        {children}
      </main>
      <FooterComponent/>
    </Fragment>
  )
}