import { Fragment, ReactNode, useState } from "react"
import Head from "next/head";
import { useRouter } from 'next/router'
import HeaderComponent from "@/components/header";
import FooterComponent from "@/components/footer"
import ShortCart from "./short-cart";
import { useContextUser } from "@/hooks/useContextUser";

type Props = {
  children: ReactNode
}
export default function BodyTemplate({ children }: Props) {
  const context = useContextUser()
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <main>
        <HeaderComponent/>
        <div>
          <div className="short-cart" hidden={context.hidden}>
            <div className="short-cart-header">
              <div style={{width:"90%"}}>Meu Carrinho</div>
              <div style={{width:"10%", cursor:"pointer"}} onClick={() => context.setHidden(!context.hidden)}>X</div>
            </div>
              <ShortCart/>
            <div className="short-cart-footer">
              <div className="buttons">
                <a className="buttonCheckout" href={context.user? '/shipping': '/signin'}>Concluir Compra</a>
                <a className="clearCart" href="#" onClick={()=> context.clearCart()}>Limpar Carrinho</a>
              </div>
            </div>
          </div>
          {children}
        </div>

      </main>
      <FooterComponent/>
    </Fragment>
  )
}